# Imagen base con Python 3.10
FROM python:3.10

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Instalar las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Comando que se ejecuta cuando el contenedor inicia
CMD ["python", "train.py"]